DELETE http://localhost:3003/api/blogs/6990611ea6ede0a2f2d97aab
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1lc3Nzc3NzaWlpIiwiaWQiOiI2OTkwMzk1ODkwYzJjMTdjNjg1YmUzOTMiLCJpYXQiOjE3NzEwODU4MDB9.Mb9fvX4ttBpQGxw76Z-p5CFp2mdkz7D2m8I4RNqLyFA